saveExact: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 5.0.1
  vite-plus: 1.0.0
  "@vitest/browser-playwright": 5.0.1
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: false
  workerd: false
minimumReleaseAgeExclude:
  - hono@4.13.13
  - "@oxc-transform-react/binding-android-arm-eabi@0.153.0"
  - "@oxc-transform-react/binding-android-arm64@0.153.0"
  - "@oxc-transform-react/binding-darwin-arm64@0.153.0"
  - "@oxc-transform-react/binding-darwin-x64@0.153.0"
  - "@oxc-transform-react/binding-freebsd-x64@0.153.0"
  - "@oxc-transform-react/binding-linux-arm-gnueabihf@0.153.0"
  - "@oxc-transform-react/binding-linux-arm-musleabihf@0.153.0"
  - "@oxc-transform-react/binding-linux-arm64-gnu@0.153.0"
  - "@oxc-transform-react/binding-linux-arm64-musl@0.153.0"
  - "@oxc-transform-react/binding-linux-ppc64-gnu@0.153.0"
  - "@oxc-transform-react/binding-linux-riscv64-gnu@0.153.0"
  - "@oxc-transform-react/binding-linux-riscv64-musl@0.153.0"
  - "@oxc-transform-react/binding-linux-s390x-gnu@0.153.0"
  - "@oxc-transform-react/binding-linux-x64-gnu@0.153.0"
  - "@oxc-transform-react/binding-linux-x64-musl@0.153.0"
  - "@oxc-transform-react/binding-openharmony-arm64@0.153.0"
  - "@oxc-transform-react/binding-win32-arm64-msvc@0.153.0"
  - "@oxc-transform-react/binding-win32-ia32-msvc@0.153.0"
  - "@oxc-transform-react/binding-win32-x64-msvc@0.153.0"
  - "@scalar/client-side-rendering@0.4.9 || 0.4.10"
  - "@scalar/helpers@0.16.1 || 0.16.2"
  - "@scalar/hono-api-reference@0.12.10 || 0.12.11"
  - "@scalar/schemas@0.13.0 || 0.13.1"
  - "@scalar/types@0.23.0 || 0.23.1"
  - "@vitejs/plugin-react@6.1.2"
  - oxc-transform-react@0.153.0
  - "@hono/node-server@2.1.4"
  - playwright-core@1.64.0
  - playwright@1.64.0
  - "@cloudflare/vite-plugin@1.63.1"
  - miniflare@5.20261006.1-alpha
  - wrangler@4.149.0
